---
title: "Chapter 9"
author: "Kyounghun Bae"
date: '2020 2 27 '
output: html_document
---

# Option Strategies




## Passive Strategies





### Option Strategies






####Option Strategies
* Dynamic Strategies are those which are rebalanced as underlying asset prices move and/or as time passes
* Passive Strategies refer to portfolios that are formed and held until option's expiration







#### Passive Strategies
* Six basic profit diagrams used to analyze passive strategies
  + Buy(Long) underlying asset
  + Sell(Short) underlying asset
  + Buy/Sell call
  + Buy/Sell put






#### Long/Short underlying asset
* Long asset 
  + Profit at time $T$
\[\pi_T = S_T - S e^{\alpha T} \in [- S e^{\alpha T}, \infty )\] 
* Short asset
  + Profit at time $T$ 
\[\pi_T = -S_T + S e^{\alpha T } \in (-\infty,  S e^{ \alpha T}]\]







#### Long Call
* Long call
\[\pi_T = \begin{cases}
    \tilde{S}_T - K - c e^{r T} ,& \text{if } \tilde{S}_T \geq K\\
    -c e^{r T},              & \text{if } \tilde{S}_T < K
\end{cases}\]
* Profit range
\[ \pi_T \in [-c e^{r T}, \infty) \]
* Breakeven price
\[ BP = K + c e^{r T }\]








#### Short Call
* Short call
\[\pi_T = \begin{cases}
    -(\tilde{S}_T - K - c e^{r T}) ,& \text{if } \tilde{S}_T \geq K\\
    c e^{r T},              & \text{if } \tilde{S}_T < K
\end{cases}\]
* Profit range
\[ \pi_T \in (-\infty,  c e^{r T} ] \]
* Breakeven price
\[ BP = K + c e^{r T }\]







#### Long $n$ Calls
* Long $n$ calls
\[\pi_T = \begin{cases}
    n(\tilde{S}_T - K - c e^{r T}) ,& \text{if } \tilde{S}_T \geq K\\
    -n c e^{r T},              & \text{if } \tilde{S}_T < K
\end{cases}\]
* Profit range
\[ \pi_T \in [-n c e^{r T}, \infty) \]
* Breakeven price
\[ BP = K + c e^{r T }\]







#### Long Put
* Long put
\[\pi_T = \begin{cases}
    -p e^{r T} ,& \text{if } \tilde{S}_T \geq K\\
    K - \tilde{S}_T  - p e^{r T},              & \text{if } \tilde{S}_T < K
\end{cases}\]
* Profit range
\[ \pi_T \in [-p e^{rT}, K - p e^{r T}] \]
* Breakeven price
\[ BP = K -p e^{r T }\]









#### Short Put
* Short put
\[\pi_T = \begin{cases}
    p e^{r T} ,& \text{if } \tilde{S}_T \geq K\\
    -(K - \tilde{S}_T  - p e^{r T}),              & \text{if } \tilde{S}_T < K
\end{cases}\]
* Profit range
\[ \pi_T \in [-( K - p e^{r T}) , p e^{rT}] \]
* Breakeven price
\[ BP = K -p e^{r T }\]








#### Synthetic Forward
* Buying call and selling put with same exercise price
* Profit function
\[\pi_T =  \tilde{S}_T - K - (c-p) e^{r T} \]
* Profit function for long forward
\[\pi_T = \tilde{S}_T - F \]
    + The forward contract has a zero premium, while the synthetic forward requires that we pay the net option premium 
    + With the forward contract, we pay the forward price, while with the synthetic forward we pay the strike price







### Passive Strategies





#### Covered Call
* Covered Call is long asset and short call
* Covered Call looks like short put
* Profit function
\[\pi_T = \begin{cases}
    -Se^{\alpha T} + K + c e^{r T} ,& \text{if } \tilde{S}_T \geq K\\
    \tilde{S}_T -Se^{\alpha T}  +c e^{r T},    & \text{if } \tilde{S}_T < K
\end{cases}\]
* Profit range
\[ \pi_T \in [-Se^{\alpha T} + c e^{rT} , -S e^{\alpha T} + K + ce^{rT} ]\]
* Breakeven price
\[BP = S e^{\alpha T} - c e^{rT} \]






  
#### Protective Put
* Protective put is long asset and long put
* Protective put looks like long call
* Profit function
\[\pi_T = \begin{cases}
    \tilde{S}_T - Se^{\alpha T} -p e^{r T} ,& \text{if } \tilde{S}_T \geq K\\
     K - S e ^{\alpha T}   - p e^{r T},              & \text{if } \tilde{S}_T < K
\end{cases}\]
* Profit range
\[ \pi_T \in [K - S e ^{\alpha T}   - p e^{r T} , \infty )\]
* Breakeven price
\[ BP = S e^{\alpha T} + p e^{rT} \]







#### Spreads
* Spread is a position consisting of only calls or only puts, in which some options are purchased and some written
* Bull spread
    + Long one call (put) and short other call(put) with higher exercise price
    + Bet that the price of underlying asset will increase
* Bear spread
    + Short one call (put) and long other call(put) with higher exercise price
    + Bet that the price of underlying asset will decrease








#### Collar
* Collar is the purchase of a put option and the sale of a call with a higher strike price, with both options having the same underlying asset and having the same expiration date
* Collar represents a bet that the price of the underlying asset will decrease and resembles a short forward
* Collar depth is the difference is the difference between the call and put strikes








#### Collar
* Collars are frequently used to implement insurance strategies
    + Collard stock : buying a collar when we own the stock
    + Consider CEOs who own the company's stock 
    + Collard stock looks like a bull spread
* Zero cost collars
    + Cost for buying collars : $c(K_2) - p(K_1)$ where $K_2 > K_1$
    + Buying $K_1 = S$ put and find call option with exercise price $K_2$ such that $c(K_2) = p(K_1)$








#### Volatility spread
* Options can be used to create positions that are nondirectional with respect to the underlying asset
    + Straddles
    + Strangles
    +  Butterfly spreads
* Who would use nondirectional positions?
    + Investors who do not care whether the stock goes up or down, but only how much it moves, i.e., who speculate on volatility








#### Straddle
* Buying a call and a put with the same exercise price and time to expiration
* Straddle is a bet that volatility will be high relative to the market's assessment
* Breakeven price
\begin{eqnarray*}
BE_l & = & K - (c + p) e^{rT} \\
BE_u & =  & K + (c + p) e^{rT}
\end{eqnarray*}








#### Strangle
* Buying a OTM call and a put with the same exercise price and time to expiration
* Strangle can be used to reduce the high premium cost, associated with a straddle 
* Breakeven price ($K_1 < K_2)$
\begin{eqnarray*}
BE_l & = & K_1 - (c + p) e^{rT} \\
BE_u & =  & K_2 + (c + p) e^{rT}
\end{eqnarray*}








#### Butterfly spreads
* Write a straddle + Add a strangle = insured written straddle
* Butterfly spread insures against large losses on a straddle







### Breakeven probabilities







#### Breakeven probabilities
* Profit diagrams show various strategies have breakeven prices
* Apply mechanics of BSM to compute breakeven probabilities
* Consider ATM staddle 
    + Asset($S$) and Exercise price ($K$) : \$50
    + expected asset return ($\alpha$) : 8\%
    + risk free rate ($r$) : 6\%
    + income rate ($\delta$) : 2\%
    + Time to maturity ($T$) : 3 months
    + Volatility ($\sigma$) : 30 \% 







#### Breakeven probabilities
* BSM call and put prices are
\[ c = 3.214 \text{ and } p = 2.719\]
* Breakeven points are
\begin{eqnarray*}
BE_l & = &  50 - (3.214+2.719) e^{0.06(0.25)} = 43.978 \\
BE_u & =  &  50 + (3.214+2.719) e^{0.06(0.25)} =  56.022
\end{eqnarray*}







#### Breakeven probabilities
* Probability of positive profit
\begin{eqnarray*}
Pr(S_T \leq BE_l \text{ or } S_T \geq BE_u) & = & N(-d_l) + N(d_u) \end{eqnarray*}
\begin{eqnarray*}
d_l & = &  \frac{\ln\left(\frac{Se^{\alpha T}}{BE_l} \right) - \frac{1}{2} \sigma^2  T}{\sigma \sqrt{T}} \\
d_u & = &   \frac{\ln\left(\frac{Se^{\alpha T}}{BE_u} \right)-\frac{1}{2} \sigma^2 T}{\sigma \sqrt{T}}
\end{eqnarray*}







#### Breakeven probabilities
* Risk Neutral Probability
\[ \alpha = r - \delta\]
* Risk Averse (Real-World) Probability
\[\alpha = E[R_S] - \delta \]








#### Breakeven probabilities
* Risk Neutral Probability : 42.01\%
\begin{eqnarray*}
Pr(S_T \leq 43.978) & = & 19.84\% \\
Pr(S_T \geq 56.022) & = & 22.17\%
\end{eqnarray*}
* Risk Averse (Real-World) Probability : 42.10 \%
\begin{eqnarray*}
Pr(S_T \leq 43.978) & = & 18.93\% \\
Pr(S_T \geq 56.022) & = & 23.17\%
\end{eqnarray*}







### Summary








#### Summary
* Passive strategies refer to portfolios that are formed and held until option's expiration
* Passive strategies can be analyzed using six basic profit diagrams
  + Long/Short asset
  + Long/Short call
  + Long/Short put

