---
title: "Chapter 7"
author: "Kyounghun Bae"
date: '2020 2 11 '
output: html_document
---

# Black-Scholes Option Pricing

#### Purpose
* Develop European-style option valuation formula
  + The Black-Scholes formula is a limiting case of the binomial formula(infinitely many periods) for the price of a European option. 
  + Called "Black-Scholes" or "Black-Scholes/Merton" model
* Key ideas are
  + Risk-free hedge and risk neutral valuation
  + Log-normal asset price distribution mechanics
  + BSM option valuation formula and its variants
  
  


#### Black-Scholes Assumptions
* Assumptions about stock return distribution
  + Continuously compounded returns on the stock are normally distributed and independent over time, i.e. stock prices are log-normally distributed.
  + The volatility of continuously compounded returns is known and constant
  + Future dividends are known, either as dollar amount or as a fixed dividend yield
  
  


#### Black-Scholes Assumptions
* Assumptions about the economic environment
  + The risk-free rate is known and constant
  + There are no transaction costs or taxes
  + It is possible to short-sell costlessly and to borrow at the risk-free rate
  
  



#### Black-Scholes Model
* Under risk-neutrality, current call value is 
\[c = e^{-r T} E[\tilde{c}_T]\]
* $E[\tilde{c}_T]$ is the expected terminal call price based on asset price distribution
* Terminal call value is 
\[\tilde{c}_T = 
\begin{cases}
    \tilde{S}_T - K ,& \text{if } \tilde{S}_T \geq K\\
    0,              & \text{if } \tilde{S}_T < K
    
    


#### Black-Scholes Model
* Expected terminal call value of exercise price $K$ is
  + E[\tilde{c}_T] & = & E[\tilde{S}_T - K | S_T > K] Pr(S_T > K) \\
& =& E[\tilde{S}_T | S_T > K] Pr(S_T > K) \\ 
& & - E[K | S_T > K] Pr(S_T > K) \\
& =& E[\tilde{S}_T | S_T > K] Pr(S_T > K) \\ 
& & - K  Pr(S_T > K)
* Result does not depend on asset price distribution.




#### Lognormal distribution
* Black-Scholes(1973) assume that asset price is lognormally distributed at option's expiration.
  + Lognormal distribution is a probability distribution of a random variable whose logarithm is normally distributed
  + Suppose random variable $\tilde{Y} \in (0, \infty)$. If $\ln(\tilde{Y})$ is normally distributed, then $\tilde{Y}$ is lognormlly distributed. 




#### Lognormal distribution
* The logarithmic function computes returns from prices
\[ r_{t+1} = \ln \left( \frac{S_{t+1}}{S_t}\right) \]
* Asset prices are always positive $\Rightarrow$ We can assume that asset prices are **lognormally** distributed
* Continuously compounded returns are assumed to be **normally** distributed




 
#### Lognormal distribution
* Under lognormal distribution, the unconditional expected price of the asset at time $T$ is 
\[E[\tilde{S}_T] = S e^{(\alpha - \delta) T}   \]   
* $\alpha - \delta$ : \textbf{Continuously compounded expected  return} on the stock
\[ \ln \left[E \left( S_T/S \right)\right] = (\alpha - \delta)T \]
* \textbf{Expected continuously compounded return} on the stock
\[ E \left (  \ln \left[ S_T/S\right]\right) = E[r_T] = (\mu - \delta) T  \] 
* $\alpha$ and $\mu$ 
\[ \alpha = \mu + \frac{1}{2} \sigma^2 \text{ or } \mu = \alpha - \frac{1}{2} \sigma^2 \]






#### Expected value for Call option
* Under lognormality, expected value is 
\[E[\tilde{c}_T] = S e^{(\alpha-\delta) T} N(d_1) - K N(d_2)  \]
where
\[ d_1 = \frac{\ln\left(\frac{S}{K} \right) +  \left(\alpha - \delta +  \frac{1}{2} \sigma^2  \right)T}{\sigma \sqrt{T}} \]
\[d_2 = d_1 - \sigma \sqrt{T} \]





#### Standard Normal Distribution $N(d)$
* Use $z$ to represent a random variable that has a standard normal distribution
\[E[\tilde{z}] = 0 \text{ and } Var(\tilde{z}) = 1 \] 
* The value of the cumulative normal distribution $N(d)$ equals to the probability $P(z < d)$ of a number $z$ drawn from the normal distribution to be less than $d$.
\[N(d) = \int_{-\infty}^d \frac{1}{\sqrt{2 \pi}} e^{-\frac{1}{2}x^2} dx \]
* $N(-\infty) = 0$ and $N(\infty)$ = 1
* Normal density is symmetric
\[ N(-d) = 1- N(d)\] 





#### Standard Normal Distribution $N(d)$
* $N(d)$ is cumulative normal probability. Area under curve to left of $d$
* In Excel, use "**=NORMSDIST(d)**"

#### Interpretation of terms
* Recall
\[E[\tilde{c}_T] = E[\tilde{S}_T| S_T > K] Pr(S_T > K) - \bf{\underline{K Pr(S_T > K)}}\]
* Compare with
\[E[\tilde{c}_T] = S e^{(\alpha-\delta) T} N(d_1) -\bf{ \underline{K N(d_2)}} \]
* Implies
\[Pr(S_T > K) =  N(d_2) \]






#### Interpretation of terms
* Recall
\[E[\tilde{c}_T] = \underline{ \bf{E[\tilde{S}_T| S_T > K] Pr(S_T > K)}}  - K Pr(S_T > K) \]
* Compare with
\[E[\tilde{c}_T] = \underline{\bf{S e^{(\alpha-\delta) T} N(d_1)}} - K N(d_2)  \]
* Implies
\[E[\tilde{S}_T| S_T > K] Pr(S_T > K) = S e^{(\alpha-\delta) T} N(d_1)  \]






#### Interpretation of terms
* In general,
\[E[\tilde{S}_T] = S e^{(\alpha - \delta) T} \neq  E[\tilde{S}_T| S_T > K] \]
* Under lognormal asset prices
\[ E[\tilde{S}_T| S_T > K]  = S e^{(\alpha - \delta) T} \frac{N(d_1)}{N(d_2)}  \]
* Thus, 
\[E[\tilde{S}_T| S_T > K] Pr(S_T > K) = S e^{(\alpha-\delta) T} N(d_1)  \]





#### Illustration
* Suppose that an asset has a current price of 100, an expected rate of return of 6\%, an income rate of 1 \%, and a volatility rate of 30 \%. 
* The expected asset price at the end of three months
* The probability of asset price being above or below 100
* The expected asset price conditional on the asset price being exceed 100 at the end of three months






#### Illustration
* The expected asset price at the end of three months
\[ E[\tilde{S}_{3 Months}] =100 e^{(0.06 - 0.01) 3/12} = 101.258\]
* The probability of asset price being above or below 100 
\begin{eqnarray*}
Pr(\tilde{S}_{3 Months} > 100) & = &  N(d_2) = 50.33\%\\
Pr(\tilde{S}_{3 Months} < 100) & = &  1 - N(d_2) = 49.67\%
\end{eqnarray*}
\begin{eqnarray*}
d_1 & = & \frac{\ln\left(\frac{100}{100} \right) +  \left(0.06 - 0.01 +  \frac{1}{2} 0.3^2  \right) 3/12}{0.3 \sqrt{3/12}} =0.158 \\
d_2 & =& d_1 - 0.3 \sqrt{3/12} = 0.008
\end{eqnarray*}






#### Illustration
* The expected asset price conditional on the asset price being exceed 100 at the end of three months
\begin{eqnarray*}
N(d_1) & = & 0.563 \\
N(d_2) & = & 0.503 
\end{eqnarray*}
\begin{eqnarray*}
E[\tilde{S}_{3 Months} | S_{3 Months} > 100] & = & Se^{(0.06-0.01)3/12} \frac{N(d_1)}{N(d_2)} \\
& = & 113.244 \\
\end{eqnarray*}







#### Call option price
* Take present value of expected future value to get European-style call formula
\[ c = e^{-r T} E[\tilde{C}_T ]\]
* Thus,
\[ c = S e^{(-r + \alpha-\delta) T} N(d_1) - K e^{-r T}N(d_2)\]
where
\[ d_1 = \frac{\ln\left(\frac{S}{K} \right) +  \left(\alpha - \delta +  \frac{1}{2} \sigma^2  \right)T}{\sigma \sqrt{T}} \]
\[d_2 = d_1 - \sigma \sqrt{T} \]






#### Black-Scholes Formula
* Black and Scholes(1973) value call on non-dividend paying stock. 
* Set $\alpha = r$ and $\delta = 0$
\[ c = S   N(d_1) - K e^{-r T}N(d_2)\]
where
\[ d_1 = \frac{\ln\left(\frac{S}{K} \right) +  \left(r +  \frac{1}{2} \sigma^2  \right)T}{\sigma \sqrt{T}} \]
\[d_2 = d_1 - \sigma \sqrt{T} \]


#### Futures option valuation
* Black (1975)  values call on futures. 
* Set $\alpha = 0$ and $\delta = 0$
\[ c = e^{-r T} [ F N(d_1) - K N(d_2)]\]
where
\[ d_1 = \frac{\ln\left(\frac{F}{K} \right) +   \frac{1}{2} \sigma^2  T}{\sigma \sqrt{T}} \]
\[d_2 = d_1 - \sigma \sqrt{T} \]






#### Stock index option valuation
* Merton(1973) values call on index. 
* Set $\alpha = r$  
\[ c = S e^{-\delta T}  N(d_1) - K e^{-r T}N(d_2)\]
where
\[ d_1 = \frac{\ln\left(\frac{S}{K} \right) +  \left(r - \delta +  \frac{1}{2} \sigma^2  \right)T}{\sigma \sqrt{T}} \]
\[d_2 = d_1 - \sigma \sqrt{T} \]








#### Currency option valuation
* Garman and Kohlhagen(1983) value call on foreign currency. 
* Set $\alpha = r_d$ and $\delta = r_f$  
\[ c = S e^{-r_f T}  N(d_1) - K e^{-r_d T}N(d_2)\]
where
\[ d_1 = \frac{\ln\left(\frac{S}{K} \right) +  \left(r_d - r_f +  \frac{1}{2} \sigma^2  \right)T}{\sigma \sqrt{T}} \]
\[d_2 = d_1 - \sigma \sqrt{T} \]






#### Black-Scholes/Merton(BSM) Model
* BSM value of European-style call is
\[ c = S e^{-\delta T} N(d_1) - K e^{-r T} N(d_2) \]
where 
\[ d_1 = \frac{\ln\left(\frac{S}{K} \right) +  \left(r - \delta +  \frac{1}{2} \sigma^2  \right)T}{\sigma \sqrt{T}} \]
\[d_2 = d_1 - \sigma \sqrt{T} \]






#### Black-Scholes/Merton(BSM) Model
* Re-arrange expression for upper integral limit 
\begin{eqnarray*}
d_1 &= &  \frac{\ln\left(\frac{S}{K} \right) +  \left(r - \delta +  \frac{1}{2} \sigma^2  \right)T}{\sigma \sqrt{T}} \\
& = &  \frac{\ln\left(\frac{S e^{-\delta T}}{K e^{-r T}} \right) +  \frac{1}{2} \sigma^2   T}{\sigma \sqrt{T}} 
\end{eqnarray*} 






#### Black-Scholes/Merton(BSM) Model
* BSM value of European-style call is
\[ c = S e^{-\delta T} N(d_1) - K e^{-r T} N(d_2) \]
where 
\[ d_1 = \frac{\ln\left(\frac{S e^{-\delta T}}{K e^{-r T}} \right) +  \frac{1}{2} \sigma^2   T}{\sigma \sqrt{T}}  \]
\[d_2 = d_1 - \sigma \sqrt{T} \]







#### Black-Scholes/Merton(BSM) Model
* European-style put formula follows directly from

  + Put-call parity
  + European-style call formula
\begin{eqnarray*}
p & = & K e^{-r T} - S e^{-\delta T} +c \\
& = & K e^{-r T} - S e^{-\delta T} + S e^{-\delta T} N(d_1) - K e^{-r T} N(d_2) \\
& =& K e^{-r T} \left[1- N(d_2) \right]- S e^{-\delta T} \left[ 1-N(d_1)\right] \\
& = & K e^{-r T} N(-d_2)- S e^{-\delta T} N(-d_1)
\end{eqnarray*}






#### Black-Scholes/Merton(BSM) Model
* BSM value of European-style put is
\[ p = K e^{-r T} N(-d_2)-S e^{-\delta T} N(-d_1) \]
where 
\[ d_1 = \frac{\ln\left(\frac{S e^{-\delta T}}{K e^{-r T}} \right) +  \frac{1}{2} \sigma^2   T}{\sigma \sqrt{T}}  \]
\[d_2 = d_1 - \sigma \sqrt{T} \]







#### Illustration
* Value call and put options with $ K = 40$ and $T = 3$ months.
* Assume stock price is 41.00, stock pays no dividends, and stock's volatility rate is 30\% annually.
* Assume interest rate is 8 \% annually. 
  + Black Scholes Merton Option Pricing.xlsx
  + Sheet : Option Valuation.






#### Illustration
* $S e^{-\delta T}$ and $Ke^{-r T} $ are
\[ S e^{-0 (3/12)} = 41 \text{ and } K e^{-0.08 (3/12)} = 39.21\]
* $N(d_1)$ and $N(d_2)$ are
\begin{eqnarray*}
d_1 & = & \frac{\ln\left(\frac{41}{39.21} \right) + 0.5  (0.3^2)   (0.25)}{0.3 \sqrt{0.25}} = 0.373 \\
d_2 & = & 0.373 - 0.3\sqrt{0.25} = 0.223 
\end{eqnarray*}
\begin{eqnarray*}
N(d_1) & = & N(0.373) = 0.6454\\
N(d_2) & = & N(0.223) = 0.5882
\end{eqnarray*}






#### Illustration
* Call option price
\begin{eqnarray*}
c & =& S N(d_1) - K e^{-rT} N(d_2) \\
 & = & 41 (0.6454) - 39.21 (0.5882) \\
 & =& 3.399
\end{eqnarray*}
* Put option price
\begin{eqnarray*}
p & =& K e^{-rT} N(-d_2) - S N(-d_1) \\
 & = & 39.21 (1-0.5882) - 41(1-0.6454) \\
 & =& 1.607
\end{eqnarray*}






#### Black-Scholes/Merton(BSM) Model
* Standard call option is portfolio consisting of two simpler options
\begin{eqnarray*}
c &= &  S e^{-\delta T} N(d_1) - X e^{-r T } N(d_2) \\
& =& \text{Asset-or-Nothing Call} - \text{Cash-or-Nothing Call}\\
p & =&  K e^{-r T} N(-d_2)-S e^{-\delta T} N(-d_1) \\
& = & \text{Cash-or-Nothing Put} - \text{Asset-or-Nothing Put}  
\end{eqnarray*}







#### Binary options
* Asset-or-Nothing(AON) option
  + AON call(put) is an option that pays a unit of the asset if the asset price is greater(less) than the strike price($K$) at expiration or zero otherwise.
* Cash-or-Nothing(CON) option
  +  CON call(put) is an option that pays a fixed amount of cash ($x$) if the asset price is greater (less) than the strike price ($K$) at expiration or zero otherwise.






#### Asset-or-Nothing option 
* Asset-or-Nothing call has payoffs
\[\tilde{c}_T^{AON} = 
\begin{cases}
    \tilde{S}_T  ,& \text{if } \tilde{S}_T \geq K\\
    0,              & \text{if } \tilde{S}_T < K
\end{cases}
\]
* Asset-or-Nothing put has payoffs
\[\tilde{p}_T^{AON} = 
\begin{cases}
    0  ,& \text{if } \tilde{S}_T \geq K\\
    \tilde{S}_T,              & \text{if } \tilde{S}_T < K
\end{cases}
\]






#### Cash-or-Nothing option 
* $x$ Cash-or-Nothing call has payoffs
\[x \tilde{c}_T^{CON} = 
\begin{cases}
    x  ,& \text{if } \tilde{S}_T \geq K\\
    0,              & \text{if } \tilde{S}_T < K
\end{cases}
\]
* $x$ Cash-or-Nothing put has payoffs
\[x \tilde{p}_T^{CON} = 
\begin{cases}
    0  ,& \text{if } \tilde{S}_T \geq K\\
    x,              & \text{if } \tilde{S}_T < K
\end{cases}
\]







#### Values of binary options
* Buying standard call option is like buying asset-or-nothing call with strike price $K$ and selling $K$ cash-or-nothing calls with strike price $K$. 
* Under no-arbitrage principle
\begin{eqnarray*}
c & =& c^{AON} - K c^{CON} \\
& =& Se^{-\delta T} N(d_1) - K e^{-r T} N(d_2)
\end{eqnarray*}
* Similarly
\begin{eqnarray*}
p & =&  K p^{CON} - p^{AON} \\
& =& K e^{-r T} N(-d_2) - Se^{-\delta T} N(-d_1)
\end{eqnarray*}







#### Illustration
* Suppose your company offers you one of two incentive plans.
  + you would receive a cash bonus of \$ 120 after six months if the firm's share price exceeds \$110. 
  + you would receive one share of stock after six months if the firm's share price exceeds \$110. 
* The company's current share price is \$ 100 per share, its volatility 20\%, and its dividend yield is 0\%. Assuming risk-free rate is 3\%, which plan is the best for you?






#### Illustration
* For the cash bonus, it is the Cash-or-Nothing call option
* For the stock bonus, it is the Asset-or-Nothing call option
* $N(d_1)$ and $N(d_2)$ are
\begin{eqnarray*}
d_1 & = & \frac{\ln\left(\frac{100}{110e^{-0.03(0.5)}} \right) +   0.5(0.2^2)  (0.5)}{0.2 \sqrt{0.5}} = -0.4972 \\
d_2 & = & -0.4972 - 0.2\sqrt{0.5} = -0.6386 
\end{eqnarray*}
\begin{eqnarray*}
N(d_1) & = & N(-0.4972) = 0.3095\\
N(d_2) & = & N(-0.6386) = 0.2615
\end{eqnarray*}






#### Illustration
* For the cash bonus, its current value is
\[ 120 c^{CON} = 120 e^{-0.03(0.5)} (0.2615) = 30.918\]
* For the stock bonus, its current value is
\[  c^{AON} = 100  (0.3095) = 30.954\]
* Thus, the second option (stock bonus) is better option. 






#### Applying the model
* To use BSM formula to value options,we need estimates of
  + asset price : $S$
  + exercise price : $K$
  + time to expiration : $T$
  + income rate : $\delta$
  + interest rate : $r$
  + volatility : $\sigma$






#### Applying the model
* Some parameters are terms of option contracts          + exercise price : $K$
  + time to expiration : $T$
* Some parameters are easily accessible market prices
  + asset price : $S$ $\Rightarrow$ Use current bid/ask midpoint or last traded price
  + income rate : $\delta$ $\Rightarrow$ Use dividend yield rate, foreign interest rate, lease rate etc. 
  + interest rate : $r$ $\Rightarrow$ Use continuously compounded T-bill rate 






#### Applying the model
* One parameter is more troublesome to estimate than others
  + volatility : $\sigma$ 
* Estimating volatility
  + Historical volatility
  + Implied volatility






#### Volatility
* Volatility is unobservable
* Option prices can be quite sensitive to volatility
* One approach is to compute historical volatility
  + One problem with historical volatility is that expected future volatility can be different from historical volatility
* Alternatively, we can calculate implied volatility, which is the volatility that, when put into BSM formula, yields the observed option price






#### Historical Volatility
* The logarithmic function computes daily returns from daily prices
\[r_{t+1} = \ln(S_{t+1}/S_{t})\]
* Since returns are additive, annual return is
\[r_{annual} = \sum_{t=1}^{252} r_t = \sum_{t=1}^{252} \ln (S_{t}/S_{t-1}) = \ln(S_{252}/S_0) \]
* The variance of the annual return is
\[Var(r_{annual}) = Var\left( \sum_{t=1}^{252} r_t\right)\]






#### Historical Volatility
* Suppose that returns are uncorrelated over time and that each day has the same variance of returns
\[Var(r_{annual}) = 252 Var(r_t) \]
* Taking the square root of both sides yields
\[\sigma = \sqrt{252} \sigma_{daily}\]
* The term $\sqrt{252}$ should be modified depending the frequency of data
  + From monthly price data : $\sqrt{12}$
  + From weekly price data :$\sqrt{52}$






#### Historical Volatility
* 1. Take observations $S_0, S_1, \cdots , S_T$ at interval of $\Delta t$ years. (e.g. for daily data $\Delta t = 1/252$)
* 2. Calculate the continuously compounded return in each interval as 
\[r_t = \ln(S_t / S_{t-1}) \text{ for } t = 1,2, \cdots, T\]
* 3. Calculate the standard deviation, $\hat{\sigma}$, of the $r_t$'s 
* 4. The annualized historical volatility is 
\[\sigma = \frac{1}{\sqrt{\Delta t} } \hat{\sigma} \]






#### Historical Volatility
* Compute mean return from data. Use "=AVERAGE()"
\[\hat{\mu} = \frac{1}{T} \sum_{t=1}^T r_t \]
* Compute standard deviation. Use "=STDEV()"
\[\hat{\sigma} = \sqrt{\frac{1}{T-1} \sum_{t=1}^{T} (r_t - \hat{\mu})^2}  \]
* To annualize volatility, multiply by square root of number of calendar days(months, weeks, etc. ) in one year






#### Historical Volatility-EWMA
* Computing volatility from standard deviation assumes the constant volatility through time.
* Volatility appears to be changing over time.
* If volatility is changing, we want to emphasize more recent observations. 
* One way to consider time-varying volatility is to compute an \textit{Exponentially Weighted Moving Average}(EWMA) of the squared stock returns.  






#### Historical Volatility-EWMA
* Equal weighted squared returns
\[\hat{\sigma} = \sqrt{\frac{1}{T} \sum_{t=1}^{T} r_t^2} \]
* Exponentially weighted moving average volatility
\[\hat{\sigma}_t = \sqrt{\sum_{i=1}^n \left[\frac{(1-\lambda) \lambda^{i-1}}{\sum_{j=1}^n (1-\lambda) \lambda^{j-1}} \right] r_{t-i}^2  } \]
  + The lower is the value of $\lambda$, the higher is the weight placed on the most recent data.






#### Illustration
* Compute historical volatilities for AAPL
* Download five-year daily price data from **finance.yahoo.com**
* Use the adjusted price series which are close prices adjusted for dividends and stock-splits. 
  + If there are no adjusted prices, you should adjust observed closed prices for cash dividends and stock splits after getting the distribution information. 
* Based on adjusted close prices, compute continuously compounded returns. 






#### Illustration
* Historical Volatility.xlsx
* Sheet : Historical Volatility.






#### Illustration
* Estimates depend on length of return history

|Data (Length) |N|StDev (Daily)|StDev (Annualized)|
|:---:|:---:|:---:|:---:|
|All data | 1,257 | 1.69\% | 26.85\% |
|One year |251  | 1.40\% | 22.20\% |
|90 days | 90 | 1.26\% |  20.04\% |
|30 days |30 | 0.95\% | 15.05\% |







#### Illustration
* Historical Volatility.xlsx
* Sheet : EWMA.






#### Illustration
* Volatility of Apple returns appeared to be lower later in the year. 

|$\lambda$| EWMA (Daily) | EWMA (Annualized) |
|:---:|:---:|:---:
|0.25| 0.35\% | 5.56\% |
|0.50 | 0.51\% | 8.11\% |
|0.75 |0.64\% | 10.20\% |






#### Implied Volatility
* Implied volatility is computed from observed option prices
* Set option prices equal to formula value and solve for $\sigma$
\[c = f(S, K, T, r, \delta, \sigma)\]
where 
  + $c$ : observed call option price
  + $f()$: BSM formula
  + $S$ : observed stock price
  + $K$ and $T$ : contract parameters
  + $r$ : risk-free rate
  + $\delta$ : dividend yield






#### Illustration
* Download AAPL option prices from CBOE website
  + http://www.cboe.com/DelayedQuote/QuoteTableDownload.aspx
* Implied Volatility.xlsx
* Sheet : IV.





#### Implied Volatility
* Some practical uses of implied volatility include
  + Use the implied volatility from an option with an observable
price to calculate the price of another option on the same underlying asset
  + Use implied volatility as a quick way to describe the level of
options prices on a given underlying asset: you could quote
option prices in terms of volatility, rather than as a dollar
price
  + Checking the uniformity of implied volatilities across various
options on the same underlying assets allows one to verify
the validity of the pricing model in pricing those options






#### How are asset prices distributed?
* BSM model assumes that the asset prices are lognormally distributed
* Implied volatilities differ for options with different exercise prices
  + stock prices may not be lognormally distributed
  + Standard normal distribution 
    + Mean : 0 
    + Standard Deviation : 1
    + Skewness : 0
    + Kurtosis : 3
* Plot the continuously compounded returns as a histogram and see whether the resulting distribution apears normal






#### Illustration
* Empirical Distribution.xlsx
* Sheet : AAPL






#### Illustration
* The histogram for normalized daily returns of AAPL doesn't appear exactly normal. 





#### How are asset prices distributed?
* Some possible explanations for returns appearing nonnormal
  + Stock prices can jump discretely from time to time
  + Asset returns are normally distributed, but with a variance that changes over time
* Although continuously compounded returns do not appear tp be exactly normal, the BSM model and the accompanying assumption of lognormality is used frequently. 





#### Summary
* Use risk-neutrality and lognormal asset price distribution to value European-style options.
  + Black-Scholes stock option formula
  + Black futures option formula
  + Merton constant dividend yield option formula
  + Garman/Kohlhagen currency option formula
* The contribution of Black-Scholes was not the particular formula but rather the appearance of the risk-free rate in the formula





#### Summary
* Applying option valuation models require estimates of   + exercise price($K$) and time to expiration ($T$)
  + underlying asset price($S$)
  + income rate ($\delta$)
  + interest rate ($r$)
  + volatility($\sigma$)
    + Historical volatility
    + Implied valatility





 