---
title: "Untitled"
author: "hyo"
date: '2020 3 13 '
output: html_document
---

---
title: "Untitled"
author: "hyo"
date: '2020 3 13 '
output: html_document
---
# Exotic Options


### Exotic Options

#### Exotic Options
* Nonstandard options
* Exotic options solve particular business problems that an ordinary option does not
* They are often constructed by tweaking ordinary options in minor ways


#### Exotic Options
* To understand exotic options, you should ask questions like
  + How does the exotic option payoff compare to that of a standard option?
  + Can the exotic option be approximated by a portfolio of other options?
  + Is the exotic option cheap or expensive relative to standard options?
  + What is the rationale for the use of the exotic option?
  + How easily can the exotic option be hedged?




#### Asian options
* The payoff of an Asian option is based on the average price over some period of time
* There are eight basic kinds of Asian options
  + Put or Call
  + Geometric or arithmetic average
    + Arithmetic Average : $A(T) = 1/N \sum_{i=1}^N S_{ih}$
    + Geometric Average : $G(T) = (S_{h} \times S_{2h} \times \cdots S_{Nh})^{1/N}$
* Average asset price is used in place of underlying price or the strike price


#### Asian options
* Average used as the asset price : Average price option
  + Geometric average price call = $\max(0, G(T)- K)$
  + Geometric average price put = $\max(0, K- G(T))$
* Average used as the strike price : Average strike option
  + Geometric average strike call = $\max(0, S_T - G_K(T))$
  + Geometric average strike put = $\max(0, G_K(T) - S_T)$




#### Asian options
* Situations when Asian options are useful
  + When a business cares about the average exchange rate over time
  + When a single price at a point in time might be subject to manipulation
  + When price swings are frequent due to thin markets
* Asian options are less valuable than otherwise equivalent ordinary options
  + the average price of the underlying asset is less volatile than the asset price itself



#### Asian options
* XYZ's currency hedging problem
  + XYZ has monthly revenue of 100 million euro, and cost in dollars
  + $x_t$ is the dollar price of a euro at time $t$
  + In one year, the converted amount in dollars is
\[ \text{100m euro} \left( \sum_{i=1}^{12} x_i e^{r (12-i)/12} \right) \]
  + If we ignore interest, what we are trying to hedge is
\[ \sum_{i=1}^{12} x_i = 12 \times \underbrace{\left( \frac{\sum_{i=1}^{12} x_i}{12} \right)}_{\text{month-end arithmetic average exchange rate}} \]



#### Asian options
* A solution for XYZ
  + XYZ receives euros $\Rightarrow$ profits are reduced if the euro depricates
  + Construct an Asian put option that puts a floor $K$, on the average exchange rate received. 
\[\max \left( 0, K - \frac{1}{12} \sum_{i=1}^{12} x_i \right)\]


#### Barrier options
* Barrier option has a payoff depending upon whether, over the lifer of the option, the price of the underlying asset reaches a specified level, called the barrier
  + path-dependent
  + Since barrier puts and calls never pay more than standard puts and calls, they are no more expensive than standard puts and calls
  + Widely used in practice



#### Barrier options
* Knock-out options : go out of existence(are "knocked-out") if the asset price reaches barrier
  + down-and-out : if the asset price falls to reach the barrier
  + up-and-out : if the asset price rises to reach the barrier
* Knock-in options : come into existence(are "knocked-in") if the barrier is touched
  + down-and-in : if the asset price falls to reach the barrier
  + up-and-in : if the asset price rises to reach the barrier




#### Compound Options
* Consider compound call on call with exercise price $x$ matured at $t_1$
  + Exercise price for underlying asset : $K$
  + Maturity for underlying asset : $T - t_1$ 
* Payoff for compound on call at time $t_1$ 
\[ \max( C(S_{t_1}, K, T-t_1) - x, 0)\]



#### Gap Options
* A gap call option pays $S_T-K_1$ when $S_T > K_2$
\item The value of a gap call is 
\[ c = S e^{-\delta T} N(d_1) - K_1 e^{-r T} N(d_2) \]
where 
\[ d_1 = \frac{\ln\left(\frac{S}{K_2} \right) +  \left(r - \delta +  \frac{1}{2} \sigma^2  \right)T}{\sigma \sqrt{T}} \]
\[d_2 = d_1 - \sigma \sqrt{T} \]



#### Exchange Options
* Pays off only if the underlying asset outperforms some other asset (benchmark) 
* The payoff at maturity is 
\[ \max(S_T- K_T,0 )\]
\item The value of an European exchange call is
\[ c = S e^{-\delta_S T} N(d_1) - K e^{-\delta_K T} N(d_2) \]
where 
\[ d_1 = \frac{\ln\left(\frac{S e^{-\delta_S T}}{K e^{-\delta_K T}} \right) +   \frac{1}{2} \sigma^2  T}{\sigma \sqrt{T}} \]
\[d_2 = d_1 - \sigma \sqrt{T} \]
\[\sigma = \sqrt{\sigma_S^2 + \sigma_K^2 -2 \rho \sigma_S \sigma_K }\]




#### Exotic Options
* Many nonstandard options exist in the OTC markets
  + Contingent pay options
  + Forward-start options
  + Ratchet options
  + Chooser options
  + Options on the maximum and the minimum
  + Lookback options



#### Valuation of exotic options
* Exotic options can be valued under the BSM risk neutral and lognormal distribution framework
  + Some exotic options have analytical solutions 
    + Gap option, Exchange option, and etc.
  + Some path-dependent options are valued numerically
    + Monte Carlo simulation



#### Measuring Risk
* Compute Greek as change in option value $OV$ as a result of changing relevant risk factor $k$ by $\epsilon$.
\begin{eqnarray*}
Greek_k &= & \frac{OV(k+ \epsilon)- OV(k-\epsilon)}{ (k+\epsilon) -(k-\epsilon)}\\
& = & \frac{OV(k+ \epsilon)- OV(k-\epsilon)}{ 2 \epsilon}
\end{eqnarray*}
where $k = S, \sigma, r, \delta, T$. 


### Summary

#### Summary
* Exotic options are created by altering the contractual terms of a standard option
* Exotic options permit hedging solutions tailored to specific problems and speculation tailored to particular views
* Compare exotic options with standard options
  + Difference and Similarity
  + Prices 
  + Who use exotic options? 



#### Summary
* Exotic options are also valued under the BSM risk neutral and lognormal distribution framework.   + Some exotic options have analytical solutions (closed-form solutions)
  + Other exotic options must be valued numerically (for e.g. Monte Carlo Simulation) 











